### ISSUE TITLE
Issues starting bot

### ISSUE THREAD

**Issue by tomearl98** [Guichaguri/DiscordDJ#18]
Upon running start_bot.sh, I'm greeted with the following: 
/<redacted>/DiscordDJ/runtime/DiscordDJ.js:127
    shCh = textCh.filter(c => c.id == shCh || c.name == shCh);
                            ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
Press [Enter] to close...

**Comment by Guichaguri** [comment]
Duplicate from #16
