### ISSUE TITLE
syntax error: unexpected token

### ISSUE THREAD

**Issue by KNGRSM** [Guichaguri/DiscordDJ#20]
shCh = textCh.filter(c => c.id == shCh || c.name == shCh);
                            ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

is this normal that it throws an error on the > ???

**Comment by Guichaguri** [comment]
Duplicate from #16
