### ISSUE TITLE
read ECONNRESET

### ISSUE THREAD

**Issue by KNGRSM** [Guichaguri/DiscordDJ#22]
{ [String: '97049313879797760']
  id: [Getter],
  username: [Getter],
  discriminator: [Getter],
  avatar: [Getter],
  guild_id: [Getter],
  roles: [Getter],
  mute: [Getter],
  deaf: [Getter],
  joined_at: [Getter] }
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at Pipe.onread (net.js:544:26)

trying to /yt /youtube a youtube link results in this error. can you provide any help on this please?

**Comment by Guichaguri** [comment]
I will look into this. For now, use /add instead. Works pretty much the same way

**Comment by KNGRSM** [comment]
the same problem occurs using /add or !add

**Comment by Guichaguri** [comment]
Can you send me the `npm-debug.log` file that was generated by this crash?

**Comment by KNGRSM** [comment]
there doesn't seem to be a npm-debug.log created

**Comment by KNGRSM** [comment]
does this help?

**Comment by Guichaguri** [comment]
I think it's something to do with the encoder.
Try playing a file
`!file [path]`

**Comment by ShiftBladez** [comment]
same things occurs

**Comment by Guichaguri** [comment]
You specified the wrong path for the encoder. It will accept any executable file, but only FFmpeg or avconv will work

**Comment by ShiftBladez** [comment]
![screenshot 8](https://cloud.githubusercontent.com/assets/16998918/12847263/ffc480be-cbdf-11e5-84a7-d664f40f3343.png)

**Comment by KNGRSM** [comment]
@Guichaguri what do you mean wrong path for the encoder, where do I set up the path to the encoder? All I did was install libav-tools.

**Comment by Guichaguri** [comment]
I'll make a quick fix, if it doesn't work, it's something to do with Discordie.
It seems like the bot is not fully connected to the voice channel.

**Comment by ShiftBladez** [comment]
this is more of a point i wanna make if you look at the log for the update ptb, i dont what they did but i believe from what it says they made it easier to use music bots, maybe it maybe helpful for your bot ?

**Comment by Guichaguri** [comment]
I can't find it. I know they were implementing configurable bit rates, that would help music bots for better audio quality. I'm still waiting for this feature to implement in DiscordDJ. Until that, i'm making it stable and easy to use. (also, a clean code is always a good idea)

**Comment by ShiftBladez** [comment]
oh ok
