### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by itslukej** [Guichaguri/DiscordDJ#33]
/home/<>/other/runtime/DiscordDJ.js:127
    shCh = textCh.filter(c => c.id == shCh || c.name == shCh);
                           ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:953:3

**Comment by Guichaguri** [comment]
Duplicate from #16
