### ISSUE TITLE
Some questions + soundcloud crashes bot

### ISSUE THREAD

**Issue by ciruz** [Guichaguri/DiscordDJ#35]
Hi @Guichaguri,

I recently tested out a lot of Discord bots, but yours has the easiest installation + configuration (assist).

Now I have some questons, first of all, I added some youtube videos and after that I get a nice private message from the bot, but nothing happens, the bot doesnt stream any sound at all.

Is there something like a start command, I didnt find anything in the source code or in your command list ( https://gist.github.com/Guichaguri/00c22e4d8f9378dba056 ).

What's up with that dj-role/list-role in the configuration file, to the bot need a own role for people allowed to controll the bot? 

And after adding a Soundcloud link, via ``!soundcloud <url>`` the bot crashed with this error in console:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:443
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1053:14)
Press [Enter] to close...
```

Thanks! :smile:

**Comment by Neko-urself** [comment]
hmm im on windows and i get this,

    events.js:154
          throw er; // Unhandled 'error' event
          ^

    Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:

        at exports._errnoException (util.js:856:11)
        at WriteWrap.afterWrite (net.js:763:14)
     Press any key to continue . . .

**Comment by ciruz** [comment]
Not for me, on Windows i get the same error:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:443
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1053:14)
```

I read in another issue that you need a Soundcloud API key, but right now you dont have to possibility to set one in the config file. So I just assume that soundcloud integration is not 100% finished yet.

@Neko-urself what I read about your error is that you access an https link over wrong port (not 443)

**Comment by Guichaguri** [comment]
Soundcloud API keys are not configurable yet (because i'm lazy), but that is coming in the next version.
@ciruz have you tried installing Libav instead of FFmpeg?

`dj-role` and `list-role` are experimental roles for the current DJ and who is in the Wait list
![Roles](http://i.imgur.com/2QJig7B.png)

Custom permissions is another thing that is planned.

The installation method and the config are going to change to make it even easier
https://www.youtube.com/watch?v=tNJg3TQxaRw

**Comment by ciruz** [comment]
Wow @Guichaguri looks good, will this be self hosted then? This reminds me a little of Gravebot, you can invite a bot from them (and hosted by them) into your channel.

I'll try install libav later when I'm at home, but is there some kind of debug / error log that i can activate? It works so well on Windows and on Linux it just play no sound without any error, thats a bit weird.

**Comment by Guichaguri** [comment]
"Self hosted" is one of the plans for the bot, it will just remain this way for now. The plan for this installation is that it will open in your browser and wait until you are done.

It doesn't have debug/error logs yet. I should've implemented this a long time ago...

**Comment by Neko-urself** [comment]
any idea how to fix my thingy?

**Comment by Guichaguri** [comment]
@Neko-urself it seems like it's a bug in Node.js. Are you using the latest release?
Also, I found [this](http://stackoverflow.com/questions/15166950/unable-to-establish-ssl-connection-how-do-i-fix-my-ssl-cert)

**Comment by Neko-urself** [comment]
im using latest stable 5.6
ill try what you linked me thanks

**Comment by ciruz** [comment]
Hey @Guichaguri, i tried it with libav, same problem, no sound, no crash, no nothing.

Any other ideas? Maybe a problem with a npm package or permissions?

**Comment by Guichaguri** [comment]
I have no idea what could be causing it. You'll have to wait until I implement debug logs, sorry :/
Maybe reinstalling DiscordDJ can solve the problem?

**Comment by ciruz** [comment]
I reinstalled it, cloned it from git but also tried your zip file from the [development build](https://github.com/Guichaguri/DiscordDJ/releases), in the installation process he finds a encoder, so really no idea too.

**Comment by Neko-urself** [comment]
i still havent fixed mine. . .
ugh i have no knowledge of OpenSSL

**Comment by Guichaguri** [comment]
Soundcloud keys added in [v0.0.4](https://github.com/Guichaguri/DiscordDJ/releases/tag/v0.0.4) (4b69ea2eeaa92bebbac235381e0f6310c7f720d2)

**Comment by Neko-urself** [comment]
ummmm http://puu.sh/ndd4o/e26c96d1dc.png
i dont see no soundcloud audio?

**Comment by Neko-urself** [comment]
i checked without-ffmpeg version, its there, i just used that one

**Comment by Guichaguri** [comment]
@ciruz
Does your problem persist in [v0.0.5](https://github.com/Guichaguri/DiscordDJ/releases/tag/v0.0.5)?

**Comment by SparkYDevtk** [comment]
Hi!
Error: connect ECONNREFUSED 127.0.0.1:443
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)


v0.0.5

**Comment by Guichaguri** [comment]
@SparkYDevtk The old DiscordDJ version is broken since the official Discord API was released. I'm working on a recode, but it will take some time. Sorry for the inconvenience.
