### ISSUE TITLE
Error in every version (Probably just me)

### ISSUE THREAD

**Issue by aidowalnut** [Guichaguri/DiscordDJ#51]
I get this error with windows-withoutffmpeg
The error is:
module.js:341
    throw err;
    ^

Error: Cannot find module 'discordie'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Aidan\Documents\DiscordBots\DiscordDJ\lib\Logic\DJManager.js:3:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
 Press any key to continue . . .

And this one, after running setup-bot and then running start-bot using version windows-withffmpeg

C:\Users\Aidan\Documents\DiscordBots\DiscordDJ\runtime\DiscordDJ.js:33
    if(!Utils.exists(config['decoder-path'])) {
                           ^

TypeError: Cannot read property 'decoder-path' of null
    at initDecoders (C:\Users\Aidan\Documents\DiscordBots\DiscordDJ\runtime\DiscordDJ.js:33:28)
    at Object.<anonymous> (C:\Users\Aidan\Documents\DiscordBots\DiscordDJ\runtime\DiscordDJ.js:324:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
 Press any key to continue . . .

I would appreciate any help.

**Comment by Guichaguri** [comment]
You need to install it before running. Run `setup-bot.bat`

**Comment by aidowalnut** [comment]
@Guichaguri I did. That works fine, and then when I run the but I get this big blob of text and then it closes. I can't read the text though because it closes so fast.

**Comment by Guichaguri** [comment]
Try to open command line and execute: `setup-bot.bat`. It will not close, then you can send me the logs.

**Comment by aidowalnut** [comment]
@Guichaguri  Ok, here is the error.

> discord-dj@0.0.5 start C:\Users\Aidan\Documents\DiscordBots\DiscordDJ
> node ./runtime/DiscordDJ.js

C:\Users\Aidan\Documents\DiscordBots\DiscordDJ\runtime\DiscordDJ.js:33
    if(!Utils.exists(config['decoder-path'])) {
                           ^

TypeError: Cannot read property 'decoder-path' of null
    at initDecoders (C:\Users\Aidan\Documents\DiscordBots\DiscordDJ\runtime\DiscordDJ.js:33:28)
    at Object.<anonymous> (C:\Users\Aidan\Documents\DiscordBots\DiscordDJ\runtime\DiscordDJ.js:324:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! discord-dj@0.0.5 start: `node ./runtime/DiscordDJ.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-dj@0.0.5 start script 'node ./runtime/DiscordDJ.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the discord-dj package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./runtime/DiscordDJ.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs discord-dj
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls discord-dj
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Aidan\Documents\DiscordBots\DiscordDJ\npm-debug.log

**Comment by aidowalnut** [comment]
@Guichaguri Any updates on the issue?
