### ISSUE TITLE
WHY

### ISSUE THREAD

**Issue by ShiftBladez** [Guichaguri/DiscordDJ#53]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.12
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart discord-dj@0.0.4
6 info start discord-dj@0.0.4
7 verbose unsafe-perm in lifecycle true
8 info discord-dj@0.0.4 Failed to exec start script
9 verbose stack Error: discord-dj@0.0.4 start: `node ./runtime/DiscordDJ.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid discord-dj@0.0.4
11 verbose cwd C:\Users\Suleman\Downloads
12 error Windows_NT 10.0.10586
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.2.6
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error discord-dj@0.0.4 start: `node ./runtime/DiscordDJ.js`
17 error Exit status 1
18 error Failed at the discord-dj@0.0.4 start script 'node ./runtime/DiscordDJ.js'.
18 error This is most likely a problem with the discord-dj package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./runtime/DiscordDJ.js
18 error You can get their info via:
18 error     npm owner ls discord-dj
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by ShiftBladez** [comment]
its not working
