### ISSUE TITLE
Similar bug to Issue #53

### ISSUE THREAD

**Issue by Heimdyll** [Guichaguri/DiscordDJ#54]
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.6.0
3 info using node@v5.7.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle discord-dj@0.0.5~prestart: discord-dj@0.0.5
6 silly lifecycle discord-dj@0.0.5~prestart: no script for prestart, continuing
7 info lifecycle discord-dj@0.0.5~start: discord-dj@0.0.5
8 verbose lifecycle discord-dj@0.0.5~start: unsafe-perm in lifecycle true
9 verbose lifecycle discord-dj@0.0.5~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\DiscordBots\DiscordDJ-master\windows-with-ffmpeg\node_modules\.bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\Connor\AppData\Local\Programs\Python\Python35;C:\Users\Connor\AppData\Local\Programs\Python\Python35\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter;C:\Windows\SYSTEM32;C:\Windows;C:\Windows\SYSTEM32\WBEM;C:\Windows\SYSTEM32\WINDOWSPOWERSHELL\V1.0\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Users\Connor\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Skype\Phone\;D:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\GtkSharp\2.12\bin;D:\Program Files\Git\cmd;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files\nodejs\;C:\Ruby22-x64\bin;C:\Ruby193\bin;C:\Users\Connor\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\Connor\AppData\Local\Programs\Python\Python35\;C:\Users\Connor\AppData\Roaming\npm
10 verbose lifecycle discord-dj@0.0.5~start: CWD: D:\DiscordBots\DiscordDJ-master\windows-with-ffmpeg
11 silly lifecycle discord-dj@0.0.5~start: Args: [ '/d /s /c', 'node ./runtime/DiscordDJ.js' ]
12 silly lifecycle discord-dj@0.0.5~start: Returned: code: 1  signal: null
13 info lifecycle discord-dj@0.0.5~start: Failed to exec start script
14 verbose stack Error: discord-dj@0.0.5 start: `node ./runtime/DiscordDJ.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid discord-dj@0.0.5
16 verbose cwd D:\DiscordBots\DiscordDJ-master\windows-with-ffmpeg
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v5.7.1
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error discord-dj@0.0.5 start: `node ./runtime/DiscordDJ.js`
22 error Exit status 1
23 error Failed at the discord-dj@0.0.5 start script 'node ./runtime/DiscordDJ.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the discord-dj package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./runtime/DiscordDJ.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs discord-dj
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls discord-dj
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by Heimdyll** [comment]
This was from the 0.0.5 build, when i pull, it runs but will not play anything. Items are queued but never started once the bot joins the server.

**Comment by Guichaguri** [comment]
Can you send me the logs from the cmd? These one is not very helpful :/
