### ISSUE TITLE
Help please! doesnt work!

### ISSUE THREAD

**Issue by riskfaktor** [Guichaguri/DiscordDJ#57]
NPM is installed!
Installing dependencies (that can take a while)

then nothing happens tried keeping it open for hours

**Comment by ciruz** [comment]
Whats your node version?

``node -v``

**Comment by riskfaktor** [comment]
tried with 5.7.1 then switched to 4.4.0. same problem

**Comment by riskfaktor** [comment]
> nmp install
SyntaxError: Unexpected identifier
    at Object.exports.createScript (vm.js:24:10)
    at REPLServer.defaultEval (repl.js:225:25)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
