### ISSUE TITLE
There is something wrong with the installer (0.0.5) windows-with-ffmpeg

### ISSUE THREAD

**Issue by ciruz** [Guichaguri/DiscordDJ#58]
when you start ``setup-bot.bat`` this happens:

```
NPM is installed!
Installing dependencies (that can take a while)

Dependencies are installed.

Now, you can start the bot.
We will help you configure the basic information

Run the bot now? [Y/N]Y

> discord-dj@0.0.5 start C:\dev\DiscordDJ
> node ./runtime/DiscordDJ.js

C:\dev\DiscordDJ\runtime\DiscordDJ.js:33
    if(!Utils.exists(config['decoder-path'])) {
                           ^

TypeError: Cannot read property 'decoder-path' of null
    at initDecoders (C:\dev\DiscordDJ\runtime\DiscordDJ.js:33:28)
    at Object.<anonymous> (C:\dev\DiscordDJ\runtime\DiscordDJ.js:324:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
```

No ``config.json`` is written.

**Comment by Guichaguri** [comment]
Duplicate from #51 
Fixed in a86e444093a29b0a75cc9f7b3f5701d9d9bf8241
